// The company page: company detail, ClickUp parent/waiver, onboarding summary.
import { clientsDelete, clientsGet, clientsPut, type ClientsResult } from "@/lib/clientsApi";

import type { FacilitySummary, OwnerInfo, ClickUpParentChange, CompanyDetailResponse } from "@/types/generated";

// Generated by ts-rs from `api/clients_detail/company/dto.rs` (unitprep-api); see
// `types/generated/README.md`. The UI keeps `CompanyDetail` for `CompanyDetailResponse`.
export type { FacilitySummary, OwnerInfo, ClickUpParentChange };
export type CompanyDetail = CompanyDetailResponse;

export async function getCompanyDetail(companyId: string): Promise<ClientsResult<CompanyDetail>> {
  return clientsGet(`/clients/${companyId}`);
}

/** Designates (or, with `null`, clears) the company's ClickUp parent
 * facility. The facility must have a ClickUp list linked. */
export async function setClickUpParent(
  companyId: string,
  facilityId: string | null,
): Promise<ClientsResult<undefined>> {
  return clientsPut(`/clients/${companyId}/clickup-parent`, { facility_id: facilityId });
}

/** Marks the company "no ClickUp project" (or clears that). */
export async function setClickUpWaiver(
  companyId: string,
  waived: boolean,
): Promise<ClientsResult<undefined>> {
  const path = `/clients/${companyId}/clickup-waiver`;
  // The PUT carries no payload -- the path is the whole request.
  return waived ? clientsPut(path, undefined) : clientsDelete(path);
}

/** Mirrors `FacilityOnboardingSummary` (unitprep-api/src/api/clients_onboarding_summary.rs). */
export interface FacilityOnboardingSummary {
  facility_id: string;
  facility_name: string;
  elavon_linked: boolean;
  elavon_next_step: string | null;
  elavon_awaiting_credentials: boolean;
  /** Credentials step done -- the sole definition of "Complete". */
  elavon_complete: boolean;
  duplicate_checks_completed: number;
}

/** Mirrors `OnboardingSummaryResponse`. */
export interface OnboardingSummaryResponse {
  facilities: FacilityOnboardingSummary[];
}

export async function getCompanyOnboardingSummary(
  companyId: string
): Promise<ClientsResult<OnboardingSummaryResponse>> {
  return clientsGet(`/clients/${companyId}/onboarding-summary`);
}
