// A facility Elavon (Merchant Account) tab.
import { clientsDelete, clientsGet, clientsPost, type ClientsResult } from "@/lib/clientsApi";

import type { ElavonPartyInfo, ElavonFinancials, ElavonCandidate, ElavonQmsCredentials, ElavonPinpadCredentials, ElavonStatusResponse } from "@/types/generated";

// Generated by ts-rs from `api/clients_elavon/dto.rs` (unitprep-api); see
// `types/generated/README.md`. `ElavonStatus` is `ElavonStatusResponse`, a serde
// `tag = "status"` enum, so the discriminant is the `status` field itself.
export type { ElavonPartyInfo, ElavonFinancials, ElavonCandidate, ElavonQmsCredentials, ElavonPinpadCredentials };
export type ElavonStatus = ElavonStatusResponse;

export async function getFacilityElavon(
  companyId: string,
  facilityId: string
): Promise<ClientsResult<ElavonStatus>> {
  return clientsGet(`/clients/${companyId}/facilities/${facilityId}/elavon`);
}

/**
 * Confirms linking a specific Merchant Account run to this facility --
 * fetches it live from PS, maps, and ingests it, same as a brand-new
 * facility's own Create flow would. 409 (`kind: "error"`) means this
 * facility already has a linked run; re-fetch `getFacilityElavon`
 * rather than retrying.
 */
export async function linkFacilityElavon(
  companyId: string,
  facilityId: string,
  merchantAccountRunId: string
): Promise<ClientsResult<void>> {
  return clientsPost(`/clients/${companyId}/facilities/${facilityId}/elavon/link`, {
    merchant_account_run_id: merchantAccountRunId,
  });
}

/**
 * Removes a facility's Merchant Account link entirely -- e.g. a wrong
 * run got linked (manually, or by automatic correlation at Create time)
 * and the manager needs to link the correct one instead. A fresh
 * `getFacilityElavon` afterward goes back to the unlinked view
 * (candidate suggestion or manual entry), same as a never-linked
 * facility. 404 (`kind: "error"`) means this facility had no linked run
 * to remove.
 */
export async function unlinkFacilityElavon(companyId: string, facilityId: string): Promise<ClientsResult<void>> {
  return clientsDelete(`/clients/${companyId}/facilities/${facilityId}/elavon/link`);
}

/**
 * Refreshes a linked facility's whole Elavon/Merchant Account picture
 * from Process Street -- rate provided, application status,
 * `credentials_added_to_qms`, financials, QMS/pinpad credentials, and
 * parties, all overwritten from a fresh PS pull (2026-09-09; the fix for
 * `credentials_added_to_qms` having no refresh path once the "Add
 * Credentials to QMS" checklist step gets completed after the initial
 * link). 409 (`kind: "error"`) means this facility has no linked
 * Merchant Account run to resync from -- link one first. A fresh
 * `getFacilityElavon` afterward shows the refreshed values.
 */
export async function resyncElavonData(companyId: string, facilityId: string): Promise<ClientsResult<void>> {
  return clientsPost(`/clients/${companyId}/facilities/${facilityId}/elavon/resync`);
}
