// A facility record and its Dropbox folder.
import { clientsGet, clientsPut, type ClientsResult } from "@/lib/clientsApi";

import type { FacilityDetailResponse } from "@/types/generated";

/** Generated by ts-rs from `FacilityDetailResponse` (unitprep-api). */
export type FacilityDetail = FacilityDetailResponse;

export async function getFacilityDetail(
  companyId: string,
  facilityId: string
): Promise<ClientsResult<FacilityDetail>> {
  return clientsGet(`/clients/${companyId}/facilities/${facilityId}`);
}

export async function updateFacilityDropboxFolder(
  companyId: string,
  facilityId: string,
  dropboxFolderUrl: string | null
): Promise<ClientsResult<void>> {
  return clientsPut(`/clients/${companyId}/facilities/${facilityId}/dropbox-folder`, {
    dropbox_folder_url: dropboxFolderUrl,
  });
}
