// A facility policies: fees, taxes, delinquency, coverage, specials.
import { clientsGet, clientsPut, type ClientsResult } from "@/lib/clientsApi";

import type {
  CommissionRow,
  CoverageTierRow,
  DelinquencyEntryInput,
  DelinquencyEntryRow,
  DelinquencyStepRow,
  FacilityPoliciesResponse,
  FeeRow,
  TaxEntryInput,
  TaxEntryRow,
  TaxesRow,
} from "@/types/generated";

// Generated by ts-rs from the Rust structs in `unitprep-api`
// (`api/clients_detail/policy_dto.rs`, `api/clients_facility_policies_edit/`)
// -- see `types/generated/README.md`. The UI keeps its older names for the
// four whose Rust names differ.
export type {
  CommissionRow,
  CoverageTierRow,
  DelinquencyEntryInput,
  DelinquencyStepRow,
  FeeRow,
  TaxEntryInput,
  TaxesRow,
};
export type TaxEntry = TaxEntryRow;
export type DelinquencyEntry = DelinquencyEntryRow;
export type FacilityPolicies = FacilityPoliciesResponse;

export async function getFacilityPolicies(
  companyId: string,
  facilityId: string
): Promise<ClientsResult<FacilityPolicies>> {
  return clientsGet(`/clients/${companyId}/facilities/${facilityId}/policies`);
}

export async function updateFacilityFees(
  companyId: string,
  facilityId: string,
  fees: FeeRow[]
): Promise<ClientsResult<void>> {
  return clientsPut(`/clients/${companyId}/facilities/${facilityId}/policies/fees`, { fees });
}

export async function updateFacilityTaxes(
  companyId: string,
  facilityId: string,
  taxes: TaxEntryInput[]
): Promise<ClientsResult<void>> {
  return clientsPut(`/clients/${companyId}/facilities/${facilityId}/policies/taxes`, { taxes });
}

export async function updateFacilityDelinquency(
  companyId: string,
  facilityId: string,
  entries: DelinquencyEntryInput[]
): Promise<ClientsResult<void>> {
  return clientsPut(`/clients/${companyId}/facilities/${facilityId}/policies/delinquency`, { entries });
}

export async function updateFacilityCoverage(
  companyId: string,
  facilityId: string,
  tiers: CoverageTierRow[],
  commission: CommissionRow | null
): Promise<ClientsResult<void>> {
  return clientsPut(`/clients/${companyId}/facilities/${facilityId}/policies/coverage`, { tiers, commission });
}

export async function updateFacilitySpecials(
  companyId: string,
  facilityId: string,
  rawText: string | null
): Promise<ClientsResult<void>> {
  return clientsPut(`/clients/${companyId}/facilities/${facilityId}/policies/specials`, { raw_text: rawText });
}
