// Shared request/response contracts with unitprep-api.
//
// The types re-exported just below (Upload/Discover/Validate/AnalyzeResponse,
// the dedup report views, and their nested shapes) are generated by ts-rs directly from the Rust
// structs they mirror -- run `npm run generate-types` after changing one of
// them, see `types/generated/README.md`. A backend field rename now shows
// up as a TypeScript error the moment you regenerate, instead of the silent
// runtime mismatch this project already went through once (the
// `output_path` removal). The remaining types below this point are still
// hand-mirrored the old way and don't yet have that guarantee.
import type { AnalyzeResponse, DedupReportView } from "./generated";

export type {
  UploadResponse,
  DiscoverResponse,
  ValidateResponse,
  AnalyzeResponse,
  UnitFileCandidate,
  FieldMappingEntry,
  Severity,
  ValidationIssue,
  FileValidationError,
  SimilarityMatch,
  AdvisoryIssue,
  FieldCategory,
  FieldName,
  BulletView,
  FlaggedGroupView,
  DuplicateTenantView,
  DuplicateCustomerRecordView,
  TypoVariantView,
  RelatednessSignal,
  RelatedTenantMemberView,
  RelatedTenantEvidenceView,
  RelatedTenantView,
  UnidentifiedMode,
  IdentifiedMatchView,
  UnidentifiedTenantView,
  UnidentifiedView,
  DedupReportView,
  DedupCheckResponse,
  RegionView,
  TierView,
  CandidateView,
  TaggerCheckResponse,
  ConfirmedSubstitution,
} from "./generated";

/** Frontend-derived summary of an upload — not a backend response shape. */
export type UploadSummary = {
  files_selected: number;
  files_uploaded: number;
  files_failed: number;
  multipart_errors: number;
  integrity_verified: boolean;
};

export type ResolveUnitFormatRequest =
  | { session_id: string; action: "confirm" }
  | {
      session_id: string;
      action: "map";
      mapping: { target: string; source: string | null }[];
    }
  | { session_id: string; action: "reset" };

// Dedup (duplicate tenant check) report types -- `DedupCheckResponse`,
// `DedupReportView` and everything they are built from are generated by
// ts-rs from `unitprep-api/src/api/dedup_view.rs` (and the field enums in
// `unitprep-dedup`), re-exported below with the rest. The request/
// classification shapes after this point are still hand-mirrored.

/** One file's verdict from `/dedup/classify-files` or
 * `/dedup/classify-dropbox-folder` (unitprep-api/src/api/dedup.rs).
 * `path` is the Dropbox full path, `null` for a locally-picked file.
 * `"supporting"` = recognized but not checkable on its own yet;
 * `"join"` = adds details (email, customer id) to the system's primary file. */
export type DedupFileClassification = {
  file_name: string;
  path: string | null;
  status: "recognized" | "unrecognized" | "unreadable";
  format_name: string | null;
  pms: string | null;
  report_name: string | null;
  role: "primary" | "supporting" | "join" | null;
  selection_priority: number;
  /** For an unrecognized file that resembles a registered format: the
   * closest one ("looks like X"). Optional so this UI also works against
   * an API that predates the field. */
  closest_vendor?: string | null;
  /** ...and which of that format's required headers the file lacks. */
  missing_headers?: string[];
};

export type DedupClassifyResponse = {
  files: DedupFileClassification[];
  suggested: {
    pms: string | null;
    /** `file_name` values to pre-check. */
    selected: string[];
    /** `file_name` -> the `file_name` of the preferred alternative it
     * loses to. */
    alternatives: Record<string, string>;
  };
};

/** Request item of `/dedup/classify-files` -- `headers` is `null` when the
 * browser can't read them (legacy `.xls`). */
export type DedupClassifyFileInput = {
  file_name: string;
  headers: string[] | null;
};

/** `GET /dedup/file-requirements` -- the informational "files required
 * for deduplication" panel's data. */
export type DedupFileRequirementsResponse = {
  vendors: {
    pms: string;
    formats: {
      name: string;
      report_name: string;
      role: "primary" | "supporting" | "join";
      selection_priority: number;
      guidance: string;
    }[];
  }[];
};

/** `"both"` returns a ZIP containing both files in one download. */
export type DedupExportFormat = "csv" | "xlsx" | "both";

/**
 * Mirrors `ToolRunSummary` (unitprep-api/src/api/tool_runs.rs) -- one
 * row of a facility's Onboarding Work tab. `report_summary` is a
 * `DedupReportView` verbatim today (the only tool that writes
 * `client_ops.tool_runs` rows yet); a later tool's differently-shaped
 * report would still fit this same field, so this isn't narrowed to
 * `DedupReportView` even though every value currently is one.
 */
export type ToolRunOutputKind = "none" | "download" | "dropbox" | "both";

type ToolRunBase = {
  id: string;
  sequence_number: number;
  actor_user_id: string | null;
  actor_first_name: string | null;
  actor_last_name: string | null;
  actor_email: string | null;
  source_file_name: string;
  source_dropbox_path: string | null;
  /** Whether this run's original source file was captured into the DB
   * -- a Dropbox-sourced path can be moved/renamed/deleted later, so
   * this is the one reference that always still works. */
  has_source_file: boolean;
  /** Whether this run kept what it needs to be re-checked (see
   * `rematchToolRun`). */
  can_rematch: boolean;
  output_kind: ToolRunOutputKind;
  output_dropbox_path: string | null;
  created_at: string;
  completed_at: string | null;
};

/** A Unit Groups run's stored summary: the analysis response plus the
 * files it read (unitprep-api/src/api/analyze.rs). */
export type UnitGroupRunSummary = AnalyzeResponse & {
  unit_files: string[];
  group_file: string | null;
};

/** A Template Tagger run's stored summary (unitprep-api/src/api/tagger.rs
 * `check_summary`); `applied_count` is null until the reviewer applies. */
export type TaggerRunSummary = {
  template_file: string;
  candidate_count: number;
  needs_review_count: number;
  tags: Record<string, number>;
  applied_count: number | null;
  preserve_blanks?: boolean;
};

/** One recorded tool run. `tool` says which summary shape `report_summary`
 * has. */
export type ToolRunSummary = ToolRunBase &
  (
    | { tool: "dedup"; report_summary: DedupReportView }
    | { tool: "unit_group"; report_summary: UnitGroupRunSummary }
    | { tool: "tagger"; report_summary: TaggerRunSummary }
  );

// QMS Template Tagging Assistant contracts -- `TaggerCheckResponse`,
// `CandidateView`, `RegionView`, `TierView` and `ConfirmedSubstitution` are
// generated by ts-rs from `unitprep-api/src/api/tagger/{views,apply}.rs`
// (re-exported above). `RegionView` is externally tagged with a unit
// "body" variant: a bare string for Body, an object for TableCell.
