// Shared request/response contracts with unitprep-api.
//
// The types re-exported just below (Upload/Discover/Validate/AnalyzeResponse,
// the dedup report views, and their nested shapes) are generated by ts-rs directly from the Rust
// structs they mirror -- run `npm run generate-types` after changing one of
// them, see `types/generated/README.md`. A backend field rename now shows
// up as a TypeScript error the moment you regenerate, instead of the silent
// runtime mismatch this project already went through once (the
// `output_path` removal). The remaining types below this point are still
// hand-mirrored the old way and don't yet have that guarantee.
import type {
  AnalyzeResponse,
  ClassifiedFileView,
  ClassifyFileInput,
  ClassifyResponse,
  DedupReportView,
  FileRequirementsResponse,
} from "./generated";

export type {
  UploadResponse,
  DiscoverResponse,
  ValidateResponse,
  AnalyzeResponse,
  UnitFileCandidate,
  FieldMappingEntry,
  Severity,
  ValidationIssue,
  FileValidationError,
  SimilarityMatch,
  AdvisoryIssue,
  FieldCategory,
  FieldName,
  BulletView,
  FlaggedGroupView,
  DuplicateTenantView,
  DuplicateCustomerRecordView,
  TypoVariantView,
  RelatednessSignal,
  RelatedTenantMemberView,
  RelatedTenantEvidenceView,
  RelatedTenantView,
  UnidentifiedMode,
  IdentifiedMatchView,
  UnidentifiedTenantView,
  UnidentifiedView,
  DedupReportView,
  DedupCheckResponse,
  RegionView,
  TierView,
  CandidateView,
  TaggerCheckResponse,
  ConfirmedSubstitution,
  FileRole,
  FileStatus,
  ClassifyFileInput,
  ClassifiedFileView,
  SuggestionView,
  ClassifyResponse,
  RequirementFormat,
  RequirementVendor,
  FileRequirementsResponse,
} from "./generated";

/** Frontend-derived summary of an upload — not a backend response shape. */
export type UploadSummary = {
  files_selected: number;
  files_uploaded: number;
  files_failed: number;
  multipart_errors: number;
  integrity_verified: boolean;
};

export type ResolveUnitFormatRequest =
  | { session_id: string; action: "confirm" }
  | {
      session_id: string;
      action: "map";
      mapping: { target: string; source: string | null }[];
    }
  | { session_id: string; action: "reset" };

// Dedup (duplicate tenant check) report types -- `DedupCheckResponse`,
// `DedupReportView` and everything they are built from are generated by
// ts-rs from `unitprep-api/src/api/dedup_view.rs` (and the field enums in
// `unitprep-dedup`), re-exported below with the rest. The request/
// classification shapes after this point are still hand-mirrored.

// File classification (`/dedup/classify-files`, `/dedup/classify-dropbox-folder`,
// `GET /dedup/file-requirements`) -- generated by ts-rs from
// `unitprep-api/src/api/dedup_files.rs` and `unitprep-dedup`'s
// `file_selection.rs`. The UI keeps its own, older names for them:
//   DedupFileClassification = ClassifiedFileView
//   DedupClassifyResponse = ClassifyResponse
//   DedupClassifyFileInput = ClassifyFileInput (`headers` is `null` when the
//     browser can't read them, i.e. a legacy `.xls`)
//   DedupFileRequirementsResponse = FileRequirementsResponse
// `role`: "supporting" = recognized but not checkable on its own yet;
// "join" = adds details (email, customer id) to the system's primary file.
// `path` is the Dropbox full path, `null` for a locally-picked file.
export type DedupFileClassification = ClassifiedFileView;
export type DedupClassifyResponse = ClassifyResponse;
export type DedupClassifyFileInput = ClassifyFileInput;
export type DedupFileRequirementsResponse = FileRequirementsResponse;

/** `"both"` returns a ZIP containing both files in one download. */
export type DedupExportFormat = "csv" | "xlsx" | "both";

/**
 * Mirrors `ToolRunSummary` (unitprep-api/src/api/tool_runs.rs) -- one
 * row of a facility's Onboarding Work tab. `report_summary` is a
 * `DedupReportView` verbatim today (the only tool that writes
 * `client_ops.tool_runs` rows yet); a later tool's differently-shaped
 * report would still fit this same field, so this isn't narrowed to
 * `DedupReportView` even though every value currently is one.
 */
export type ToolRunOutputKind = "none" | "download" | "dropbox" | "both";

type ToolRunBase = {
  id: string;
  sequence_number: number;
  actor_user_id: string | null;
  actor_first_name: string | null;
  actor_last_name: string | null;
  actor_email: string | null;
  source_file_name: string;
  source_dropbox_path: string | null;
  /** Whether this run's original source file was captured into the DB
   * -- a Dropbox-sourced path can be moved/renamed/deleted later, so
   * this is the one reference that always still works. */
  has_source_file: boolean;
  /** Whether this run kept what it needs to be re-checked (see
   * `rematchToolRun`). */
  can_rematch: boolean;
  output_kind: ToolRunOutputKind;
  output_dropbox_path: string | null;
  created_at: string;
  completed_at: string | null;
};

/** A Unit Groups run's stored summary: the analysis response plus the
 * files it read (unitprep-api/src/api/analyze.rs). */
export type UnitGroupRunSummary = AnalyzeResponse & {
  unit_files: string[];
  group_file: string | null;
};

/** A Template Tagger run's stored summary (unitprep-api/src/api/tagger.rs
 * `check_summary`); `applied_count` is null until the reviewer applies. */
export type TaggerRunSummary = {
  template_file: string;
  candidate_count: number;
  needs_review_count: number;
  tags: Record<string, number>;
  applied_count: number | null;
  preserve_blanks?: boolean;
};

/** One recorded tool run. `tool` says which summary shape `report_summary`
 * has. */
export type ToolRunSummary = ToolRunBase &
  (
    | { tool: "dedup"; report_summary: DedupReportView }
    | { tool: "unit_group"; report_summary: UnitGroupRunSummary }
    | { tool: "tagger"; report_summary: TaggerRunSummary }
  );

// QMS Template Tagging Assistant contracts -- `TaggerCheckResponse`,
// `CandidateView`, `RegionView`, `TierView` and `ConfirmedSubstitution` are
// generated by ts-rs from `unitprep-api/src/api/tagger/{views,apply}.rs`
// (re-exported above). `RegionView` is externally tagged with a unit
// "body" variant: a bare string for Body, an object for TableCell.
