// Shared request/response contracts with unitprep-api.
//
// The types re-exported just below (Upload/Discover/Validate/AnalyzeResponse
// and their nested shapes) are generated by ts-rs directly from the Rust
// structs they mirror -- run `npm run generate-types` after changing one of
// them, see `types/generated/README.md`. A backend field rename now shows
// up as a TypeScript error the moment you regenerate, instead of the silent
// runtime mismatch this project already went through once (the
// `output_path` removal). The remaining types below this point are still
// hand-mirrored the old way and don't yet have that guarantee.
export type {
  UploadResponse,
  DiscoverResponse,
  ValidateResponse,
  AnalyzeResponse,
  UnitFileCandidate,
  FieldMappingEntry,
  Severity,
  ValidationIssue,
  FileValidationError,
  SimilarityMatch,
  AdvisoryIssue,
} from "./generated";

/** Frontend-derived summary of an upload — not a backend response shape. */
export type UploadSummary = {
  files_selected: number;
  files_uploaded: number;
  files_failed: number;
  multipart_errors: number;
  integrity_verified: boolean;
};

export type ResolveUnitFormatRequest =
  | { session_id: string; action: "confirm" }
  | {
      session_id: string;
      action: "map";
      mapping: { target: string; source: string | null }[];
    }
  | { session_id: string; action: "reset" };

// Dedup (duplicate tenant check) contracts — mirror unitprep-api's
// enriched view types 1:1 (not unitprep-dedup's own raw domain types,
// which stay pure and never carry column-layout/cell-ref concepts):
//   DedupCheckResponse, DedupReportView, FlaggedGroupView, BulletView,
//   TypoVariantView, RelatedTenantView, RelatedTenantMemberView
//     -> unitprep-api/src/api/dedup.rs, dedup_view.rs
//   FieldCategory, FieldName -> unitprep-dedup/src/types/fields.rs

export type FieldCategory =
  | "Phone"
  | "Email"
  | "Address"
  | "AltContact"
  | "Company"
  | "Name";

export type FieldName =
  | "PhoneNumber"
  | "PhoneNumberPrefix"
  | "Email"
  | "AddressStreet1"
  | "AddressStreet2"
  | "AddressCity"
  | "AddressState"
  | "AddressPostalCode"
  | "AltContactFirstName"
  | "AltContactLastName"
  | "AltContactEmail"
  | "AltContactPhoneNumber"
  | "AltContactPhoneNumberPrefix"
  | "AltContactAddressStreet1"
  | "AltContactAddressStreet2"
  | "AltContactAddressCity"
  | "AltContactAddressState"
  | "AltContactAddressPostalCode"
  | "CompanyName"
  | "FirstName"
  | "LastName";

/** One plain-English sentence for a single differing field. */
export type BulletView = {
  field: FieldName;
  label: string;
  sentence: string;
  /** Cell references in the *exported* CSV/xlsx (e.g. "N22") — empty if
   * none apply. */
  cell_refs: string[];
};

export type FlaggedGroupView = {
  key: string;
  display_name: string;
  units: string[];
  /** In priority order — the order to show them in a "Mismatches: ..."
   * summary line. */
  categories: FieldCategory[];
  bullets: BulletView[];
};

export type TypoVariantView = {
  display_name_a: string;
  units_a: string[];
  display_name_b: string;
  units_b: string[];
  contact_info_matches: boolean;
  /** Which non-Name categories actually differ across the combined
   * pair — empty when `contact_info_matches` is true. Render this
   * instead of a bare matches/differs label so a pair that matches on
   * most fields and differs on one doesn't read as "nothing matches." */
  differing_categories: FieldCategory[];
  note: string;
};

export type RelatednessSignal =
  | "SharedPhone"
  | "SharedEmail"
  | "SharedAlternateContact"
  | "SharedHomeAddress";

export type RelatedTenantMemberView = {
  display_name: string;
  units: string[];
};

/**
 * One piece of a household's evidence — `members` is the specific
 * subset of the household that shares `shared_value` under `signal`,
 * which can be smaller than the household's full member list (not
 * every member necessarily shares every piece of evidence with every
 * other member directly, only transitively — see `RelatedTenantView`).
 */
export type RelatedTenantEvidenceView = {
  signal: RelatednessSignal;
  shared_value: string;
  members: RelatedTenantMemberView[];
};

/**
 * A household: two or more tenants (different name keys) connected by
 * one or more pieces of shared-value evidence — evidence of a real
 * relationship (business + owner, family, subdivided unit) that
 * neither exact-name grouping nor typo-variant similarity could catch,
 * since both hinge on name similarity. Always advisory, same as
 * `TypoVariantView`. `members` is the full household (the union across
 * every entry in `evidence`); `note` is one combined account of every
 * piece of evidence, not one note per signal.
 */
export type RelatedTenantView = {
  members: RelatedTenantMemberView[];
  evidence: RelatedTenantEvidenceView[];
  note: string;
};

export type DedupReportView = {
  total_rows: number;
  unique_tenants: number;
  multi_unit_tenants: number;
  flagged_groups: FlaggedGroupView[];
  typo_variant_candidates: TypoVariantView[];
  related_tenant_candidates: RelatedTenantView[];
};

export type DedupCheckResponse = {
  session_id: string;
  report: DedupReportView;
};

/** Mirrors `DedupDetectVendorResponse` (unitprep-api/src/api/dedup.rs) --
 * `vendor_name` is `null` when the file doesn't match any registered
 * vendor's column signature. */
export type DedupDetectVendorResponse = {
  vendor_name: string | null;
};

/** `"both"` returns a ZIP containing both files in one download. */
export type DedupExportFormat = "csv" | "xlsx" | "both";

/**
 * Mirrors `ToolRunSummary` (unitprep-api/src/api/tool_runs.rs) -- one
 * row of a facility's Onboarding Work tab. `report_summary` is a
 * `DedupReportView` verbatim today (the only tool that writes
 * `client_ops.tool_runs` rows yet); a later tool's differently-shaped
 * report would still fit this same field, so this isn't narrowed to
 * `DedupReportView` even though every value currently is one.
 */
export type ToolRunOutputKind = "none" | "download" | "dropbox";

export type ToolRunSummary = {
  id: string;
  sequence_number: number;
  tool: string;
  actor_user_id: string | null;
  actor_first_name: string | null;
  actor_last_name: string | null;
  actor_email: string | null;
  source_file_name: string;
  source_dropbox_path: string | null;
  /** Whether this run's original source file was captured into the DB
   * -- a Dropbox-sourced path can be moved/renamed/deleted later, so
   * this is the one reference that always still works. */
  has_source_file: boolean;
  report_summary: DedupReportView;
  output_kind: ToolRunOutputKind;
  output_dropbox_path: string | null;
  created_at: string;
  completed_at: string | null;
};

// QMS Template Tagging Assistant contracts — mirror unitprep-api's
// enriched view types 1:1:
//   TaggerCheckResponse, CandidateView, RegionView, TierView
//     -> unitprep-api/src/api/tagger.rs
// RegionView is externally-tagged with a unit "body" variant: a bare
// string for Body, an object for TableCell.

export type RegionView =
  | "body"
  | { table_cell: { index: number } };

export type TierView = "auto" | "needs_review";

export type CandidateView = {
  /** This candidate's position in the session's own candidate list —
   * /tagger/apply references a candidate by this same index. */
  index: number;
  region: RegionView;
  tag_key: string;
  matched_text: string;
  tier: TierView;
  snippet: string;
};

export type TaggerCheckResponse = {
  session_id: string;
  candidates: CandidateView[];
};

export type ConfirmedSubstitution = {
  candidate_index: number;
  tag_key: string;
};
