import { clientsGet, clientsPost, type ClientsResult } from "@/lib/clientsApi";

import type { DuplicateCandidate, FacilityMatch, PersonMatch, MerchantAccountMatch, SearchClientsResponse, MatchedVia } from "@/types/generated";

// Generated by ts-rs from `api/clients_search/dto.rs` (unitprep-api); see
// `types/generated/README.md`.
export type { DuplicateCandidate, FacilityMatch, PersonMatch, MerchantAccountMatch, SearchClientsResponse, MatchedVia };

export type { ClientsResult };

/** One of the three Process Street workflows a match came from. */
export type PsWorkflow = "intake" | "merchant_account" | "contract_order";

/**
 * Searches Process Street for a company/facility (by name, a live call)
 * and for a person (by name/email, against the locally-synced
 * `clients.ps_person_index`) in one round trip. See the backend's own
 * `clients_search::search_clients` doc comment for the two lookups this
 * runs and why a facility can legitimately show up under more than one
 * title across the three workflows.
 */
export async function searchClients(query: string): Promise<ClientsResult<SearchClientsResponse>> {
  return clientsGet(`/clients/search?q=${encodeURIComponent(query)}`);
}

/** One of the states `clients_sync::sync_status` reports. */
export type SyncState = "idle" | "running" | "completed" | "failed";

/** Mirrors `SyncStatusResponse` in `unitprep-api`'s `clients_sync.rs`. */
export interface SyncStatus {
  state: SyncState;
  total_runs: number;
  processed_runs: number;
  percent: number;
  error: string | null;
}

/**
 * Triggers a Process Street sync right now, rather than waiting for the
 * nightly background one. Returns as soon as the sync has *started* --
 * poll `getSyncStatus` for progress. A 409 (surfaced as `kind: "error"`)
 * means one (manual or nightly) was already running.
 *
 * `force: true` re-syncs every run in every workflow from scratch,
 * ignoring PS's own `ps_updated_at` delta check -- real Process Street
 * API cost (see `unitprep-api`'s `sync::orchestrator::sync_runs_within`
 * doc comment), so this should stay an explicit, occasional choice, not
 * the default.
 */
export async function startSync(force = false): Promise<ClientsResult<{ started: boolean }>> {
  return clientsPost(force ? "/clients/sync?force=true" : "/clients/sync");
}

/** Poll this while a sync is running to drive a progress bar. */
export async function getSyncStatus(): Promise<ClientsResult<SyncStatus>> {
  return clientsGet("/clients/sync/status");
}
