import { clientsDelete, clientsGet, clientsPost, clientsPut, type ClientsResult } from "@/lib/clientsApi";

import type { CompanySummary, ResyncConflict, PreviewResyncResponse, ConflictResolution, ApplyResyncResponse, ManualLinkWorkflow, ManualLinkRequest, ManualLinkResponse } from "@/types/generated";

// Generated by ts-rs from the Rust structs in `unitprep-api` (`api/clients_companies.rs`,
// `clients_resync/`, `clients_manual_link.rs`); see `types/generated/README.md`.
export type { CompanySummary, ResyncConflict, PreviewResyncResponse, ConflictResolution, ApplyResyncResponse, ManualLinkWorkflow, ManualLinkRequest, ManualLinkResponse };

/**
 * The real `clients.companies` list -- backs the unified `/clients`
 * page and `lib/clients.tsx`'s `useClients()` hook.
 */

/** Any authenticated caller -- see the backend module's own doc comment. */
export async function listCompanies(): Promise<ClientsResult<CompanySummary[]>> {
  return clientsGet("/clients");
}

export async function archiveCompany(companyId: string): Promise<ClientsResult<undefined>> {
  return clientsPost(`/clients/${companyId}/archive`);
}

export async function unarchiveCompany(companyId: string): Promise<ClientsResult<undefined>> {
  return clientsPost(`/clients/${companyId}/unarchive`);
}

/**
 * Marks a company's implementation completed (`completed: true`) or
 * reopens it. Both directions are idempotent on the backend
 * (`api::clients_implementation_status`); needs `client_ops.perform`.
 */
export async function setImplementationCompleted(
  companyId: string,
  completed: boolean,
): Promise<ClientsResult<undefined>> {
  const path = `/clients/${companyId}/implementation-completed`;
  // The PUT carries no payload -- the path is the whole request.
  return completed ? clientsPut(path, undefined) : clientsDelete(path);
}

/**
 * Permanently deletes a company and every facility under it -- distinct
 * from archive/unarchive above, which is reversible and keeps the row
 * around. For a genuine mistake (a test import, or one created from the
 * wrong Process Street runs), not something to reach for as routine
 * cleanup. The frontend confirms before calling this; the backend
 * itself asks for no separate confirmation of its own.
 */
export async function deleteCompany(companyId: string): Promise<ClientsResult<undefined>> {
  return clientsDelete(`/clients/${companyId}`);
}

export async function previewResync(companyId: string): Promise<ClientsResult<PreviewResyncResponse>> {
  return clientsPost(`/clients/${companyId}/resync/preview`);
}

export async function applyResync(
  companyId: string,
  resolutions: ConflictResolution[]
): Promise<ClientsResult<ApplyResyncResponse>> {
  return clientsPost(`/clients/${companyId}/resync/apply`, { resolutions });
}

/**
 * Company page's "Manual Link" button -- repoints one facility's Intake
 * or Merchant Account run to a different run id, in place, whether or
 * not it's already linked to something else. See the backend module's
 * own doc comment for why this exists alongside (not instead of) the
 * Elavon tab's own "Link Manually", which only covers the not-yet-linked
 * Merchant Account case.
 */
export async function manualLink(
  companyId: string,
  request: ManualLinkRequest
): Promise<ClientsResult<ManualLinkResponse>> {
  return clientsPost(`/clients/${companyId}/manual-link`, request);
}
