import { clientsPost, type ClientsResult } from "@/lib/clientsApi";

import type { MappedCompany, MappedFacility, PreviewedRun, PreviewClientsResponse, CreateFacilitySelection, CreateClientRequest, CreateClientResponse, PersonAssignment } from "@/types/generated";

// Generated by ts-rs from `clients/intake_mapping.rs`, `api/clients_preview.rs` and
// `api/clients_create.rs` (unitprep-api); see `types/generated/README.md`.
export type { MappedCompany, MappedFacility, PreviewedRun, PreviewClientsResponse, CreateFacilitySelection, CreateClientRequest, CreateClientResponse, PersonAssignment };

/**
 * "Add to OO" -- the preview (review) + create round trip behind the
 * confirmation screen at `/clients/new`. Kept separate from
 * `clientsSearch.ts` (finding candidates) and `clientsCompanies.ts`
 * (the resulting list) -- three different concerns sharing one small
 * fetch layer (`clientsApi.ts`), not one growing file.
 */

/**
 * `MappedFacility` minus `go_live_date`, plus this facility's own
 * reviewed People roster. Mirrors `EditableFacilityFields` in
 * `unitprep-api`'s `clients::create`: deliberately narrower than
 * `MappedFacility` so a go-live-date edit is structurally impossible to
 * submit, not just a UI convention. `people` has no `MappedFacility`
 * counterpart at all -- PS's owner/DM/manager fields carry no real
 * facility-level attribution (see `PersonAssignment`'s backend doc
 * comment), so this is a human's own reviewed pick, not a mapped value.
 */
export type EditableFacilityFields = Omit<MappedFacility, "go_live_date"> & {
  people: PersonAssignment[];
};

/**
 * One selected run to preview -- `run_name` is the raw PS title already
 * known from the search step (`FacilityMatch.run_name`), passed through
 * rather than re-derived, so the backend can correlate a Merchant
 * Account run *before* fetching this run's own Intake fields instead of
 * after. See `unitprep-api`'s `clients_preview.rs` module doc for why
 * that ordering roughly halves how long this call takes.
 */
export interface PreviewRunSelection {
  run_id: string;
  run_name: string;
  /**
   * Set when this run was one of the search page's "Potential
   * Duplicates" candidates and the user picked *this specific*
   * Merchant Account run there (`FacilityMatch.duplicate.
   * merchant_account_run_id`) -- always overrides whatever the backend
   * would otherwise auto-correlate for this run, since the ambiguity
   * search surfaced is already resolved by the time this exists. See
   * the backend's own `clients_preview.rs` module doc.
   */
  merchant_account_run_id?: string | null;
}

/**
 * Live-fetches and maps every selected Intake run for review -- writes
 * nothing. Every run comes back with both a `company` and `facility`
 * view; the confirmation screen's own Company/Facility toggle per row
 * decides which one is actually used when `createClient` is called.
 */
export async function previewClients(
  runs: PreviewRunSelection[]
): Promise<ClientsResult<PreviewClientsResponse>> {
  return clientsPost("/clients/preview", { runs });
}

/**
 * The real "Add to OO" trigger -- creates one `clients.companies` row
 * (from `company_intake_run_id` + the reviewed `company` fields) and
 * one `clients.facilities` row per entry in `facilities`. A 409
 * (surfaced as `kind: "error"`) means one or more of the selected runs
 * is already imported -- re-check with a fresh search/preview rather
 * than retrying blindly.
 */
export async function createClient(request: CreateClientRequest): Promise<ClientsResult<CreateClientResponse>> {
  return clientsPost("/clients", request);
}
