/**
 * Static reference data for the Company/Facility pages' "Field Reference"
 * help table -- every OO field sourced from Process Street, which
 * workflow/step/field it comes from, plus every real Pre-App field this
 * session's 2026-09-03 audit found that OO doesn't capture yet. This is
 * hand-maintained (like `client_ops.qms_tag`), not generated -- verified
 * against Prairie Enterprises' real Highway 20 Intake and New Merchant
 * Account runs (live PS API field/task dumps), not guessed. Update this
 * file whenever a mapping in `unitprep-api`'s `clients::intake_mapping` /
 * `clients::merchant_account_mapping` changes.
 */

export type PsWorkflow = "Intake" | "New Merchant Account";
export type MappingStatus = "mapped" | "not_yet_mapped";

export interface FieldProvenanceEntry {
  ooSection: string;
  ooField: string;
  psWorkflow: PsWorkflow;
  /** The PS checklist task/step this field (or task, for a
   * task-completion-derived field) lives under. */
  psStep: string;
  /** PS's own field key, or `null` when this OO field comes from a
   * checklist task's completion status rather than a form field. */
  psFieldKey: string | null;
  psFieldLabel: string;
  status: MappingStatus;
  notes?: string;
}

export const FIELD_PROVENANCE: FieldProvenanceEntry[] = [
  // --- Company Information (Company page) -- all Intake ---
  {
    ooSection: "Company Information",
    ooField: "Legal Name",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "What_is_the_name_of_your_Corporation_/_Business_Entity?",
    psFieldLabel: "What is the name of your Corporation / Business Entity?",
    status: "mapped",
    notes: "Falls back to Company_Name: on the same step if the first field is blank.",
  },
  {
    ooSection: "Company Information",
    ooField: "Email",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "What_is_your_Corporate_Email_Address?",
    psFieldLabel: "What is your Corporate Email Address?",
    status: "mapped",
  },
  {
    ooSection: "Company Information",
    ooField: "Phone",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "What_is_your_Corporate_Phone_Number?",
    psFieldLabel: "What is your Corporate Phone Number?",
    status: "mapped",
  },
  {
    ooSection: "Company Information",
    ooField: "Street Address",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Corporate_Street_Address:",
    psFieldLabel: "Corporate Street Address:",
    status: "mapped",
  },
  {
    ooSection: "Company Information",
    ooField: "City",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Corporate_City:",
    psFieldLabel: "Corporate City:",
    status: "mapped",
  },
  {
    ooSection: "Company Information",
    ooField: "State",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Corporate_State:",
    psFieldLabel: "Corporate State:",
    status: "mapped",
  },
  {
    ooSection: "Company Information",
    ooField: "ZIP",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Corporate_Zip:",
    psFieldLabel: "Corporate Zip:",
    status: "mapped",
  },
  {
    ooSection: "Company Information",
    ooField: "Subdomain",
    psWorkflow: "Intake",
    psStep: "DETERMINE Subdomains & Email Addresses",
    psFieldKey: "Company_Subdomain:",
    psFieldLabel: "Company Subdomain:",
    status: "mapped",
  },

  // --- Financial Information (Company page) -- all Intake ---
  {
    ooSection: "Financial Information",
    ooField: "Elavon (Merchant Account)",
    psWorkflow: "New Merchant Account",
    psStep: "(computed)",
    psFieldKey: null,
    psFieldLabel: "Whether any of this company's facilities has a linked Merchant Account run",
    status: "mapped",
    notes: "Not a single field -- read-time EXISTS check across the company's own facilities.",
  },
  {
    ooSection: "Financial Information",
    ooField: "Accepted Payment Methods",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Accepted_Payment_Methods:",
    psFieldLabel: "Accepted Payment Methods:",
    status: "mapped",
    notes: "Multi-select field -- every checked option, comma-joined.",
  },
  {
    ooSection: "Financial Information",
    ooField: "Accounting Basis",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Accounting_Basis:",
    psFieldLabel: "Accounting Basis:",
    status: "mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Payment Scheme",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Payment_Scheme:",
    psFieldLabel: "Payment Scheme:",
    status: "mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Offers Tenant Insurance",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Are_they_currently_offering_insurance/protection_to_their_tenants?",
    psFieldLabel: "Are they currently offering insurance/protection to their tenants?",
    status: "mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Insurance Provider",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Who_is_their_insurance_provider?",
    psFieldLabel: "Who is their insurance provider?",
    status: "mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Ownership Type",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Ownership_Type",
    psFieldLabel: "Ownership Type",
    status: "not_yet_mapped",
    notes: "Computed in code for company naming but never persisted to a real column or shown yet.",
  },
  {
    ooSection: "Financial Information",
    ooField: "Legal Name (Elavon's own)",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Legal_Name_2",
    psFieldLabel: "Legal Name",
    status: "not_yet_mapped",
    notes: "Computed in code for company naming but never persisted to a real column or shown yet.",
  },
  {
    ooSection: "Financial Information",
    ooField: "Business DBA",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Business_DBA",
    psFieldLabel: "Business DBA",
    status: "not_yet_mapped",
    notes: "Computed in code for company naming but never persisted to a real column or shown yet.",
  },
  {
    ooSection: "Financial Information",
    ooField: "Funding Options",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Funding_Options",
    psFieldLabel: "Funding Options",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Year Business Established",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Year_Business_Established",
    psFieldLabel: "Year Business Established",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "# of Months Business Established",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "#_of_Months_Business_Established",
    psFieldLabel: "# of Months Business Established",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Current Ownership Length",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Current_Ownership_Length",
    psFieldLabel: "Current Ownership Length",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Evidence of Legal Status",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Evidence_of_Legal_Status",
    psFieldLabel: "Evidence of Legal Status",
    status: "not_yet_mapped",
    notes: "File upload field, plus Additional_Evidence_of_Legal_Status.",
  },
  {
    ooSection: "Financial Information",
    ooField: "Legal Address (if different from Business Address)",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Legal_Address_Line_1 / _City / _State / _Zip_Code",
    psFieldLabel: "Legal Address Line 1 / City / State / Zip Code",
    status: "not_yet_mapped",
    notes: "Only answered when Legal_Address? is \"Different than Business Address\".",
  },
  {
    ooSection: "Financial Information",
    ooField: "Business Contact Name",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Business_Contact_-_First_Name / _Last_Name",
    psFieldLabel: "Business Contact - First/Last Name",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Who is the Processor",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Info",
    psFieldKey: "Who_is_the_Processor?",
    psFieldLabel: "Who is the Processor?",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "QMS / Cloud / QSX Type",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Info",
    psFieldKey: "Is_the_new_processor_account_for_QMS,_Cloud,_or_QSX?",
    psFieldLabel: "Is the new processor account for QMS, Cloud, or QSX?",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Scheduled Conversion Date",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Info",
    psFieldKey: "Scheduled_Conversion_Date",
    psFieldLabel: "Scheduled Conversion Date",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Application Type Submitted",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "What_Application_Type_Did_the_Client_Submit",
    psFieldLabel: "What Application Type Did the Client Submit",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Is Absolute Management Property",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Is_this_an_Absolute_Management_Property",
    psFieldLabel: "Is this an Absolute Management Property",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Facility Name in CRM / CRM Link",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Facility_Name_in_CRM / Facility_CRM_Link",
    psFieldLabel: "Facility Name in CRM / Facility CRM Link",
    status: "not_yet_mapped",
    notes: "CRM Link is a HubSpot deep link.",
  },
  {
    ooSection: "Financial Information",
    ooField: "Facility Website",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Your_Facility_Website",
    psFieldLabel: "Your Facility Website",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Contact Us Email / Phone",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Contact_Us_Email / Contact_Us_Phone_Number",
    psFieldLabel: "Contact Us Email / Contact Us Phone Number",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Statement Correspondence Address",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Where_should_Statements_and_Other_Correspondence_Go?",
    psFieldLabel: "Where should Statements and Other Correspondence Go?",
    status: "not_yet_mapped",
    notes: "Plus Other_Address_-_Line_1/City/State/Zip when the answer isn't \"Facility Address\".",
  },
  {
    ooSection: "Financial Information",
    ooField: "Ownership Structure Meta (25%+ signer, owner/intermediary counts)",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Does_the_signer_of_the_application_own_25%_or_more... / How_many_personal_owners... / How_many_intermediary_business_owners...",
    psFieldLabel: "Ownership structure meta questions",
    status: "not_yet_mapped",
  },

  // --- Owner(s) / Signer Information (Company page + Elavon tab) --
  {
    ooSection: "Owner(s) / Signer Information",
    ooField: "Name / Title / Ownership % / Email / Phone",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Signer_-_* / Owner_1..4_-_*",
    psFieldLabel: "Signer - First/Last Name, Title, % Ownership, Email, Home or Cell Phone",
    status: "mapped",
    notes: "One row per party slot PS actually answered (Signer, Owner 1-4).",
  },
  {
    ooSection: "Owner(s) / Signer Information",
    ooField: "SSN (encrypted, fully masked with Show/Hide)",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Signer_-_SSN / Owner_1..4_-_SSN",
    psFieldLabel: "Signer/Owner - SSN",
    status: "mapped",
    notes: "The real decrypted SSN still arrives from the API; PartyCard masks it entirely by default (no digits at all, unlike the prior \"last 4 visible\" style) and reveals the real value on click. Corrected 2026-09-03 per Boris's call -- reveal was always meant to stay, only the masked-state rendering changed.",
  },
  {
    ooSection: "Owner(s) / Signer Information",
    ooField: "Date of Birth",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Signer_-_DOB / Owner_1..4_-_DOB",
    psFieldLabel: "Signer/Owner - DOB",
    status: "mapped",
  },
  {
    ooSection: "Owner(s) / Signer Information",
    ooField: "Home Address",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Signer_-_HOME_Address / _City / _State_or_Province / _Postal_Code",
    psFieldLabel: "Signer/Owner - Home Address, City, State, Postal Code",
    status: "mapped",
  },
  {
    ooSection: "Owner(s) / Signer Information",
    ooField: "Intermediary Business Owner (name, contact, ownership %)",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Intermediary_Business_1..4_-_*",
    psFieldLabel: "Intermediary Business 1-4 - Name, Contact, Phone, Email, Ownership %",
    status: "mapped",
    notes: "No SSN/DOB/home address fields exist for a business owner in PS's own template.",
  },

  // --- Facility General (Facility page) -- all Intake ---
  {
    ooSection: "Facility General",
    ooField: "Facility Name",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Facility_Name",
    psFieldLabel: "Facility Name",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Street Address",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Facility_Street_Address:",
    psFieldLabel: "Facility Street Address:",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "City",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Facility_City:",
    psFieldLabel: "Facility City:",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "State",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Facility_State:",
    psFieldLabel: "Facility State:",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "ZIP",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Facility_Zip:",
    psFieldLabel: "Facility Zip:",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Phone",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "What_is_the_facility_phone_number?",
    psFieldLabel: "What is the facility phone number?",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Email",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "What_is_the_facility_email_address?",
    psFieldLabel: "What is the facility email address?",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Units Count",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "How_many_units_does_this_facility_have?",
    psFieldLabel: "How many units does this facility have?",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Primary Storage Offering",
    psWorkflow: "Intake",
    psStep: "Fill in Rep Only Fields",
    psFieldKey: "What_is_the_PRIMARY_storage_offering_at_this_facility?",
    psFieldLabel: "What is the PRIMARY storage offering at this facility?",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Previous PMS",
    psWorkflow: "Intake",
    psStep: "Fill in Rep Only Fields",
    psFieldKey: "What_Property_Management_Software_is_this_facility_currently_using?",
    psFieldLabel: "What Property Management Software is this facility currently using?",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Access Control System",
    psWorkflow: "Intake",
    psStep: "Fill in Rep Only Fields",
    psFieldKey: "What_Access_Control_system_are_they_using?",
    psFieldLabel: "What Access Control system are they using?",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Original Go Live Date",
    psWorkflow: "Intake",
    psStep: "Fill in Rep Only Fields",
    psFieldKey: "What_is_the_Go_Live_Date_on_the_contract?",
    psFieldLabel: "What is the Go Live Date on the contract?",
    status: "mapped",
    notes: "Read-only in OO by design -- an editable \"Updated Go Live Date\" is a separate, future field.",
  },
  {
    ooSection: "Facility General",
    ooField: "Dropbox Folder URL",
    psWorkflow: "Intake",
    psStep: "CREATE Dropbox Folders",
    psFieldKey: "Facility_Onboarding_folder_URL:",
    psFieldLabel: "Facility Onboarding folder URL:",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Subdomain",
    psWorkflow: "Intake",
    psStep: "DETERMINE Subdomains & Email Addresses",
    psFieldKey: "Facility_Subdomain:",
    psFieldLabel: "Facility Subdomain:",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Subdomain Exists in QMS",
    psWorkflow: "Intake",
    psStep: "DETERMINE Subdomains & Email Addresses",
    psFieldKey: "Does_the_Facility_Subdomain_already_exist_in_QMS?",
    psFieldLabel: "Does the Facility Subdomain already exist in QMS?",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "System Email",
    psWorkflow: "Intake",
    psStep: "DETERMINE Subdomains & Email Addresses",
    psFieldKey: "Facility_Email_Address:",
    psFieldLabel: "Facility Email Address:",
    status: "mapped",
  },

  // --- Facility Policies (Facility page) -- all Intake ---
  {
    ooSection: "Facility Policies -- Fees",
    ooField: "Security Deposit / NSF / Move-In Admin / Transfer / Cleaning / Other Fees",
    psWorkflow: "Intake",
    psStep: "B.) DLQ/Taxes/Fees/Specials",
    psFieldKey: "Security_Deposit / NSF_/_Chargeback_Fee / Move-In_Admin_Fee / Transfer_Fee / Cleaning_Fee / Any_Other_Fees:",
    psFieldLabel: "Security Deposit, NSF/Chargeback Fee, Move-In Admin Fee, Transfer Fee, Cleaning Fee, Any Other Fees",
    status: "mapped",
  },
  {
    ooSection: "Facility Policies -- Taxes",
    ooField: "Sales / Rent / Other Taxes",
    psWorkflow: "Intake",
    psStep: "B.) DLQ/Taxes/Fees/Specials",
    psFieldKey: "Is_this_facility_subject_to_sales_tax... / Does_the_facility_use_a_Rent_Tax?...",
    psFieldLabel: "Sales tax applies/rate, Rent tax applies/rate/scope, Additional One-Time/Recurring Taxes",
    status: "mapped",
  },
  {
    ooSection: "Facility Policies -- Delinquency",
    ooField: "Delinquency Steps / Notice Type / Notes",
    psWorkflow: "Intake",
    psStep: "B.) DLQ/Taxes/Fees/Specials",
    psFieldKey: "Which_type_of_late_notice_should_recur? / How_many_days_after_Paid_THRU_Date... / Add'l_Delinquency_Actions: / Delinquency_Notes:",
    psFieldLabel: "Late notice type/timing, additional delinquency actions, delinquency notes",
    status: "mapped",
  },
  {
    ooSection: "Facility Policies -- Specials",
    ooField: "Specials",
    psWorkflow: "Intake",
    psStep: "B.) DLQ/Taxes/Fees/Specials",
    psFieldKey: "Specials:",
    psFieldLabel: "Specials:",
    status: "mapped",
    notes: "One raw text blob, preserved verbatim (whitespace/indentation included).",
  },
  {
    ooSection: "Facility Policies -- Coverage",
    ooField: "Coverage Tiers (1-6)",
    psWorkflow: "Intake",
    psStep: "C.) Coverage",
    psFieldKey: "Coverage_Level_1..6_-_Cost_to_Tenant:",
    psFieldLabel: "Coverage Level 1-6 - Cost to Tenant",
    status: "mapped",
  },
  {
    ooSection: "Facility Policies -- Coverage",
    ooField: "Commission",
    psWorkflow: "Intake",
    psStep: "C.) Coverage",
    psFieldKey: "Is_Commission_a_Percentage_or_Flat_Dollar_Amount? / $_Commission_Amount: / %_Commission_Amount:",
    psFieldLabel: "Commission type, dollar amount, percent amount",
    status: "mapped",
  },

  // --- Elavon tab (Facility page) -- all New Merchant Account ---
  {
    ooSection: "Elavon",
    ooField: "Rate Provided",
    psWorkflow: "New Merchant Account",
    psStep: "What Rate was provided to the customer",
    psFieldKey: "What_Processing_Rates_did_you_provide_to_the_customer?",
    psFieldLabel: "What Processing Rates did you provide to the customer?",
    status: "mapped",
    notes: "Free text -- the exact wording (e.g. whether \"Elavon Rate:\" is typed first) varies by who filled it in.",
  },
  {
    ooSection: "Elavon",
    ooField: "Application Status",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Info",
    psFieldKey: "What_is_their_software_onboarding_status?",
    psFieldLabel: "What is their software onboarding status?",
    status: "mapped",
  },
  {
    ooSection: "Elavon",
    ooField: "Credentials Added to QMS",
    psWorkflow: "New Merchant Account",
    psStep: "Add Credentials to QMS",
    psFieldKey: null,
    psFieldLabel: "\"Add Credentials to QMS\" checklist task, Completed/NotCompleted",
    status: "mapped",
    notes: "A checklist task's own completion status, not a form field -- fixed 2026-09-03 after showing \"No\" for a facility whose step was actually done in PS.",
  },
  {
    ooSection: "Elavon",
    ooField: "EIN",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "EIN",
    psFieldLabel: "EIN",
    status: "mapped",
    notes: "Decrypted from facility_merchant_accounts.encrypted_secrets, shown unmasked (not asked to be masked, and less sensitive than a personal SSN/bank account).",
  },
  {
    ooSection: "Elavon",
    ooField: "Bank Routing Number (masked)",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Bank_Routing_Number",
    psFieldLabel: "Bank Routing Number",
    status: "mapped",
    notes: "Decrypted from encrypted_secrets, masked to its last 4 digits (mask_bank_number) before leaving the backend -- e.g. •••••0016.",
  },
  {
    ooSection: "Elavon",
    ooField: "Bank Account Number (masked)",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Bank_Account_Number",
    psFieldLabel: "Bank Account Number",
    status: "mapped",
    notes: "Same masking as Bank Routing Number above.",
  },
  {
    ooSection: "Elavon",
    ooField: "QMS Credentials (encrypted, not yet shown)",
    psWorkflow: "New Merchant Account",
    psStep: "Document Credentials",
    psFieldKey: "QUIKSTOR_Password / QSS_WEB_PIN / Pinpad_User_ID / QSS_API_Pin / MID / ACCOUNT_ID",
    psFieldLabel: "QUIKSTOR Password, QSS WEB PIN, Pinpad User ID, QSS API Pin, MID, ACCOUNT ID",
    status: "not_yet_mapped",
    notes: "Already captured + encrypted -- deliberately still no read/decrypt endpoint (scope stayed to EIN + bank numbers).",
  },
  {
    ooSection: "Elavon",
    ooField: "Total Annual Business Revenue",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Total_Annual_Business_Revenue",
    psFieldLabel: "Total Annual Business Revenue",
    status: "mapped",
    notes: "Confirmed genuinely per-facility, not company-wide (Prairie Enterprises' 3 real facilities each answered differently) -- moved here from a provisional \"Financial Information\" (Company page) placement.",
  },
  {
    ooSection: "Elavon",
    ooField: "Total Monthly Sales",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Total_Monthly_Sales",
    psFieldLabel: "Total Monthly Sales",
    status: "mapped",
  },
  {
    ooSection: "Elavon",
    ooField: "Average Credit Card Payment Amount",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Average_credit_card_payment_amount",
    psFieldLabel: "Average credit card payment amount",
    status: "mapped",
  },
  {
    ooSection: "Elavon",
    ooField: "Highest Credit Card Payment Amount",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Highest_credit_card_payment_amount",
    psFieldLabel: "Highest credit card payment amount",
    status: "mapped",
  },
  {
    ooSection: "Elavon",
    ooField: "# Times Per Year for the High CC Payment",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "#_times_per_year_for_the_high_CC_Payment",
    psFieldLabel: "# times per year for the high CC Payment",
    status: "mapped",
  },
  {
    ooSection: "Elavon",
    ooField: "Offers ACH",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Do_you_want_to_offer_ACH",
    psFieldLabel: "Do you want to offer ACH",
    status: "mapped",
  },
  {
    ooSection: "Elavon",
    ooField: "Annual Electronic Check (ACH) Volume",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Annual_Electronic_Check_Volume",
    psFieldLabel: "Annual Electronic Check Volume",
    status: "mapped",
  },
  {
    ooSection: "Elavon",
    ooField: "Average Electronic Check Amount",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Average_Electronic_Check_Amount",
    psFieldLabel: "Average Electronic Check Amount",
    status: "mapped",
  },
  {
    ooSection: "Elavon",
    ooField: "Maximum Electronic Check Amount",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Maximum_Electronic_Check_Amount",
    psFieldLabel: "Maximum Electronic Check Amount",
    status: "mapped",
  },
];
