import type { FieldProvenanceEntry } from "./types";

/** Company Information (Company page) -- all Intake. See `types.ts` for what this table is. */
export const COMPANY_FIELDS: FieldProvenanceEntry[] = [
  {
    ooSection: "Company Information",
    ooField: "Legal Name",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "What_is_the_name_of_your_Corporation_/_Business_Entity?",
    psFieldLabel: "What is the name of your Corporation / Business Entity?",
    status: "mapped",
    notes: "Falls back to Company_Name: on the same step if the first field is blank.",
  },
  {
    ooSection: "Company Information",
    ooField: "Email",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "What_is_your_Corporate_Email_Address?",
    psFieldLabel: "What is your Corporate Email Address?",
    status: "mapped",
  },
  {
    ooSection: "Company Information",
    ooField: "Phone",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "What_is_your_Corporate_Phone_Number?",
    psFieldLabel: "What is your Corporate Phone Number?",
    status: "mapped",
  },
  {
    ooSection: "Company Information",
    ooField: "Street Address",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Corporate_Street_Address:",
    psFieldLabel: "Corporate Street Address:",
    status: "mapped",
  },
  {
    ooSection: "Company Information",
    ooField: "City",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Corporate_City:",
    psFieldLabel: "Corporate City:",
    status: "mapped",
  },
  {
    ooSection: "Company Information",
    ooField: "State",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Corporate_State:",
    psFieldLabel: "Corporate State:",
    status: "mapped",
  },
  {
    ooSection: "Company Information",
    ooField: "ZIP",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Corporate_Zip:",
    psFieldLabel: "Corporate Zip:",
    status: "mapped",
  },
  {
    ooSection: "Company Information",
    ooField: "Subdomain",
    psWorkflow: "Intake",
    psStep: "DETERMINE Subdomains & Email Addresses",
    psFieldKey: "Company_Subdomain:",
    psFieldLabel: "Company Subdomain:",
    status: "mapped",
  },
  {
    ooSection: "Company Information",
    ooField: "Website",
    psWorkflow: "Intake",
    psStep: "(computed)",
    psFieldKey: null,
    psFieldLabel: "Copied from the facility's own website when the confirmation screen's fallback is accepted",
    status: "mapped",
    notes: "No PS field of its own -- offered when a facility's Corporate Info section came back entirely blank (e.g. the client answered \"Yes\" to \"Is your Corporate Name, Address, Phone Number & Email the same as this Facility?\"), copying that facility's own name/address/phone/website into the Company section instead.",
  },
];
