import type { FieldProvenanceEntry } from "./types";

/** Elavon tab (Facility page) -- all New Merchant Account. See `types.ts` for what this table is. */
export const ELAVON_FIELDS: FieldProvenanceEntry[] = [
  {
    ooSection: "Elavon",
    ooField: "Rate Provided",
    psWorkflow: "New Merchant Account",
    psStep: "What Rate was provided to the customer",
    psFieldKey: "What_Processing_Rates_did_you_provide_to_the_customer?",
    psFieldLabel: "What Processing Rates did you provide to the customer?",
    status: "mapped",
    notes: "Free text -- the exact wording (e.g. whether \"Elavon Rate:\" is typed first) varies by who filled it in.",
  },
  {
    ooSection: "Elavon",
    ooField: "Application Status",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Info",
    psFieldKey: "What_is_their_software_onboarding_status?",
    psFieldLabel: "What is their software onboarding status?",
    status: "mapped",
  },
  {
    ooSection: "Elavon",
    ooField: "Credentials Added to QMS",
    psWorkflow: "New Merchant Account",
    psStep: "Document Credentials / Add Credentials to QMS",
    psFieldKey: null,
    psFieldLabel: "Credentials checklist task (names set under Process Street settings > Task mapping), Completed/NotCompleted",
    status: "mapped",
    notes: "A checklist task's own completion status, not a form field -- fixed 2026-09-03 after showing \"No\" for a facility whose step was actually done in PS. Which task names count is editable data (new runs use \"Document Credentials\"; older runs, \"Add Credentials to QMS\"); tasks PS hides on a run are ignored.",
  },
  {
    ooSection: "Elavon",
    ooField: "EIN",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "EIN",
    psFieldLabel: "EIN",
    status: "mapped",
    notes: "Decrypted from facility_merchant_accounts.encrypted_secrets, shown unmasked (not asked to be masked, and less sensitive than a personal SSN/bank account).",
  },
  {
    ooSection: "Elavon",
    ooField: "Bank Routing Number (masked)",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Bank_Routing_Number",
    psFieldLabel: "Bank Routing Number",
    status: "mapped",
    notes: "Decrypted from encrypted_secrets, masked to its last 4 digits (mask_bank_number) before leaving the backend -- e.g. •••••0016.",
  },
  {
    ooSection: "Elavon",
    ooField: "Bank Account Number (masked)",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Bank_Account_Number",
    psFieldLabel: "Bank Account Number",
    status: "mapped",
    notes: "Same masking as Bank Routing Number above.",
  },
  {
    ooSection: "Elavon",
    ooField: "QMS Credentials (encrypted, not yet shown)",
    psWorkflow: "New Merchant Account",
    psStep: "Document Credentials",
    psFieldKey: "QUIKSTOR_Password / QSS_WEB_PIN / Pinpad_User_ID / QSS_API_Pin / MID / ACCOUNT_ID",
    psFieldLabel: "QUIKSTOR Password, QSS WEB PIN, Pinpad User ID, QSS API Pin, MID, ACCOUNT ID",
    status: "not_yet_mapped",
    notes: "Already captured + encrypted -- deliberately still no read/decrypt endpoint (scope stayed to EIN + bank numbers).",
  },
  {
    ooSection: "Elavon",
    ooField: "Total Annual Business Revenue",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Total_Annual_Business_Revenue",
    psFieldLabel: "Total Annual Business Revenue",
    status: "mapped",
    notes: "Confirmed genuinely per-facility, not company-wide (Prairie Enterprises' 3 real facilities each answered differently) -- moved here from a provisional \"Financial Information\" (Company page) placement.",
  },
  {
    ooSection: "Elavon",
    ooField: "Total Monthly Sales",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Total_Monthly_Sales",
    psFieldLabel: "Total Monthly Sales",
    status: "mapped",
  },
  {
    ooSection: "Elavon",
    ooField: "Average Credit Card Payment Amount",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Average_credit_card_payment_amount",
    psFieldLabel: "Average credit card payment amount",
    status: "mapped",
  },
  {
    ooSection: "Elavon",
    ooField: "Highest Credit Card Payment Amount",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Highest_credit_card_payment_amount",
    psFieldLabel: "Highest credit card payment amount",
    status: "mapped",
  },
  {
    ooSection: "Elavon",
    ooField: "# Times Per Year for the High CC Payment",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "#_times_per_year_for_the_high_CC_Payment",
    psFieldLabel: "# times per year for the high CC Payment",
    status: "mapped",
  },
  {
    ooSection: "Elavon",
    ooField: "Offers ACH",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Do_you_want_to_offer_ACH",
    psFieldLabel: "Do you want to offer ACH",
    status: "mapped",
  },
  {
    ooSection: "Elavon",
    ooField: "Annual Electronic Check (ACH) Volume",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Annual_Electronic_Check_Volume",
    psFieldLabel: "Annual Electronic Check Volume",
    status: "mapped",
  },
  {
    ooSection: "Elavon",
    ooField: "Average Electronic Check Amount",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Average_Electronic_Check_Amount",
    psFieldLabel: "Average Electronic Check Amount",
    status: "mapped",
  },
  {
    ooSection: "Elavon",
    ooField: "Maximum Electronic Check Amount",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Maximum_Electronic_Check_Amount",
    psFieldLabel: "Maximum Electronic Check Amount",
    status: "mapped",
  },
];
