import type { FieldProvenanceEntry } from "./types";

/** Facility General (Facility page) -- all Intake. See `types.ts` for what this table is. */
export const FACILITY_GENERAL_FIELDS: FieldProvenanceEntry[] = [
  {
    ooSection: "Facility General",
    ooField: "Facility Name",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Facility_Name",
    psFieldLabel: "Facility Name",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Street Address",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Facility_Street_Address:",
    psFieldLabel: "Facility Street Address:",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "City",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Facility_City:",
    psFieldLabel: "Facility City:",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "State",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Facility_State:",
    psFieldLabel: "Facility State:",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "ZIP",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Facility_Zip:",
    psFieldLabel: "Facility Zip:",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Phone",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "What_is_the_facility_phone_number?",
    psFieldLabel: "What is the facility phone number?",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Email",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "What_is_the_facility_email_address?",
    psFieldLabel: "What is the facility email address?",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Units Count",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "How_many_units_does_this_facility_have?",
    psFieldLabel: "How many units does this facility have?",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Primary Storage Offering",
    psWorkflow: "Intake",
    psStep: "Fill in Rep Only Fields",
    psFieldKey: "What_is_the_PRIMARY_storage_offering_at_this_facility?",
    psFieldLabel: "What is the PRIMARY storage offering at this facility?",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Previous PMS",
    psWorkflow: "Intake",
    psStep: "Fill in Rep Only Fields",
    psFieldKey: "What_Property_Management_Software_is_this_facility_currently_using?",
    psFieldLabel: "What Property Management Software is this facility currently using?",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Access Control System",
    psWorkflow: "Intake",
    psStep: "Fill in Rep Only Fields",
    psFieldKey: "What_Access_Control_system_are_they_using?",
    psFieldLabel: "What Access Control system are they using?",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Original Go Live Date",
    psWorkflow: "Intake",
    psStep: "Fill in Rep Only Fields",
    psFieldKey: "What_is_the_Go_Live_Date_on_the_contract?",
    psFieldLabel: "What is the Go Live Date on the contract?",
    status: "mapped",
    notes: "Read-only in OO by design -- an editable \"Updated Go Live Date\" is a separate, future field.",
  },
  {
    ooSection: "Facility General",
    ooField: "Dropbox Folder URL",
    psWorkflow: "Intake",
    psStep: "CREATE Dropbox Folders",
    psFieldKey: "Facility_Onboarding_folder_URL:",
    psFieldLabel: "Facility Onboarding folder URL:",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Subdomain",
    psWorkflow: "Intake",
    psStep: "DETERMINE Subdomains & Email Addresses",
    psFieldKey: "Facility_Subdomain:",
    psFieldLabel: "Facility Subdomain:",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Subdomain Exists in QMS",
    psWorkflow: "Intake",
    psStep: "DETERMINE Subdomains & Email Addresses",
    psFieldKey: "Does_the_Facility_Subdomain_already_exist_in_QMS?",
    psFieldLabel: "Does the Facility Subdomain already exist in QMS?",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "System Email",
    psWorkflow: "Intake",
    psStep: "DETERMINE Subdomains & Email Addresses",
    psFieldKey: "Facility_Email_Address:",
    psFieldLabel: "Facility Email Address:",
    status: "mapped",
  },
  {
    ooSection: "Facility General",
    ooField: "Website",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "What_is_the_URL_for_this_facility?",
    psFieldLabel: "What is the URL for this facility?",
    status: "mapped",
    notes: "The facility's real business website -- distinct from Subdomain (the QMS-hosted tenant portal).",
  },
];
