import type { FieldProvenanceEntry } from "./types";

/** Financial Information (Company page) -- all Intake. See `types.ts` for what this table is. */
export const FINANCIAL_FIELDS: FieldProvenanceEntry[] = [
  {
    ooSection: "Financial Information",
    ooField: "Elavon (Merchant Account)",
    psWorkflow: "New Merchant Account",
    psStep: "(computed)",
    psFieldKey: null,
    psFieldLabel: "Whether any of this company's facilities has a linked Merchant Account run",
    status: "mapped",
    notes: "Not a single field -- read-time EXISTS check across the company's own facilities.",
  },
  {
    ooSection: "Financial Information",
    ooField: "Accepted Payment Methods",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Accepted_Payment_Methods:",
    psFieldLabel: "Accepted Payment Methods:",
    status: "mapped",
    notes: "Multi-select field -- every checked option, comma-joined.",
  },
  {
    ooSection: "Financial Information",
    ooField: "Accounting Basis",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Accounting_Basis:",
    psFieldLabel: "Accounting Basis:",
    status: "mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Payment Scheme",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Payment_Scheme:",
    psFieldLabel: "Payment Scheme:",
    status: "mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Offers Tenant Insurance",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Are_they_currently_offering_insurance/protection_to_their_tenants?",
    psFieldLabel: "Are they currently offering insurance/protection to their tenants?",
    status: "mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Insurance Provider",
    psWorkflow: "Intake",
    psStep: "A.) Corp/Facility Info (form fill)",
    psFieldKey: "Who_is_their_insurance_provider?",
    psFieldLabel: "Who is their insurance provider?",
    status: "mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Ownership Type",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Ownership_Type",
    psFieldLabel: "Ownership Type",
    status: "not_yet_mapped",
    notes: "Computed in code for company naming but never persisted to a real column or shown yet.",
  },
  {
    ooSection: "Financial Information",
    ooField: "Legal Name (Elavon's own)",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Legal_Name_2",
    psFieldLabel: "Legal Name",
    status: "not_yet_mapped",
    notes: "Computed in code for company naming but never persisted to a real column or shown yet.",
  },
  {
    ooSection: "Financial Information",
    ooField: "Business DBA",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Business_DBA",
    psFieldLabel: "Business DBA",
    status: "not_yet_mapped",
    notes: "Computed in code for company naming but never persisted to a real column or shown yet.",
  },
  {
    ooSection: "Financial Information",
    ooField: "Funding Options",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Funding_Options",
    psFieldLabel: "Funding Options",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Year Business Established",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Year_Business_Established",
    psFieldLabel: "Year Business Established",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "# of Months Business Established",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "#_of_Months_Business_Established",
    psFieldLabel: "# of Months Business Established",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Current Ownership Length",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Current_Ownership_Length",
    psFieldLabel: "Current Ownership Length",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Evidence of Legal Status",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Evidence_of_Legal_Status",
    psFieldLabel: "Evidence of Legal Status",
    status: "not_yet_mapped",
    notes: "File upload field, plus Additional_Evidence_of_Legal_Status.",
  },
  {
    ooSection: "Financial Information",
    ooField: "Legal Address (if different from Business Address)",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Legal_Address_Line_1 / _City / _State / _Zip_Code",
    psFieldLabel: "Legal Address Line 1 / City / State / Zip Code",
    status: "not_yet_mapped",
    notes: "Only answered when Legal_Address? is \"Different than Business Address\".",
  },
  {
    ooSection: "Financial Information",
    ooField: "Business Contact Name",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Business_Contact_-_First_Name / _Last_Name",
    psFieldLabel: "Business Contact - First/Last Name",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Who is the Processor",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Info",
    psFieldKey: "Who_is_the_Processor?",
    psFieldLabel: "Who is the Processor?",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "QMS / Cloud / QSX Type",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Info",
    psFieldKey: "Is_the_new_processor_account_for_QMS,_Cloud,_or_QSX?",
    psFieldLabel: "Is the new processor account for QMS, Cloud, or QSX?",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Scheduled Conversion Date",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Info",
    psFieldKey: "Scheduled_Conversion_Date",
    psFieldLabel: "Scheduled Conversion Date",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Application Type Submitted",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "What_Application_Type_Did_the_Client_Submit",
    psFieldLabel: "What Application Type Did the Client Submit",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Is Absolute Management Property",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Is_this_an_Absolute_Management_Property",
    psFieldLabel: "Is this an Absolute Management Property",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Facility Name in CRM / CRM Link",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Facility_Name_in_CRM / Facility_CRM_Link",
    psFieldLabel: "Facility Name in CRM / Facility CRM Link",
    status: "not_yet_mapped",
    notes: "CRM Link is a HubSpot deep link.",
  },
  {
    ooSection: "Financial Information",
    ooField: "Facility Website",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Your_Facility_Website",
    psFieldLabel: "Your Facility Website",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Contact Us Email / Phone",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Contact_Us_Email / Contact_Us_Phone_Number",
    psFieldLabel: "Contact Us Email / Contact Us Phone Number",
    status: "not_yet_mapped",
  },
  {
    ooSection: "Financial Information",
    ooField: "Statement Correspondence Address",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Where_should_Statements_and_Other_Correspondence_Go?",
    psFieldLabel: "Where should Statements and Other Correspondence Go?",
    status: "not_yet_mapped",
    notes: "Plus Other_Address_-_Line_1/City/State/Zip when the answer isn't \"Facility Address\".",
  },
  {
    ooSection: "Financial Information",
    ooField: "Ownership Structure Meta (25%+ signer, owner/intermediary counts)",
    psWorkflow: "New Merchant Account",
    psStep: "Facility Information (Pre-App)",
    psFieldKey: "Does_the_signer_of_the_application_own_25%_or_more... / How_many_personal_owners... / How_many_intermediary_business_owners...",
    psFieldLabel: "Ownership structure meta questions",
    status: "not_yet_mapped",
  },
];
